# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=100, verbose_name=b'Course ID')),
                ('chatbot_url', models.CharField(blank=True, max_length=300, verbose_name=b'Chatbot URL')),
            ],
            options={
                'verbose_name': 'Course Chatbot',
                'verbose_name_plural': 'Course Chatbots',
            },
        ),
    ]
